### ISSUE TITLE
ClassNotFoundException: io.netty.util.concurrent.DefaultPromise$1

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Hyperfoil#13]
Occasionally, at the end of a run, the following exception is logged;

```
Exception in thread "nioEventLoopGroup-2-1" java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$1
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:432)
	at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:94)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:939)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: io.netty.util.concurrent.DefaultPromise$1
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrateg[
```

**Comment by johnaohara** [comment]
This occurred with a fresh build

**Comment by johnaohara** [comment]
I am not sure what is happening, as I only see a partial stack trace. But it appears that if the process is in shutdown, classloading is throwing execeptions;

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12.631 s
[INFO] Finished at: 2019-04-09T07:39:15+01:00
[INFO] ------------------------------------------------------------------------
[WARNING] An exception 'java.lang.NoClassDefFoundError: org/apache/logging/log4j/message/FormattedMessage' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.lang.NoClassDefFoundError: io/netty/buffer/PoolThreadCache$1
    at io.netty.buffer.PoolThreadCache.cache (PoolThreadCache.java:212)
    at io.netty.buffer.PoolThreadCache.add (PoolThreadCache.java:204)
    at io.netty.buffer.PoolArena.free[johara@test hyperfoil-runner]$
```

**Comment by rvansa** [comment]
Closing as stale. Reopen if you intend to work on that.

**Comment by tianxianglan** [comment]
so, do you have solved the problem?

**Comment by rvansa** [comment]
@tianxianglan No, I've closed as sort of can't-reproduce. Since the impact is very low (just message in logs during shutdown) I didn't bother to investigate much. Can you reproduce reliably/does it cause any trouble?
