### ISSUE TITLE
ControllerVerticle should show the root cause

### ISSUE THREAD

**Issue by diegolovison** [Hyperfoil/Hyperfoil#175]
When running Hyperfoil agents in OpenShift, for example, I can see in the Hyperfoil controller log the following:
```
13:43:29,464 ERROR (vert.x-eventloop-thread-1) [i.h.c.ControllerVerticle] 0000 Agent agent-one(ecd0a44d-9d54-41ae-8b5d-9c7fe8d14110) failed to initialize (RECIPIENT_FAILURE,1) io.netty.channel.StacklessClosedChannelException
    at io.vertx.core.eventbus.impl.codecs.ReplyExceptionMessageCodec.decodeFromWire(ReplyExceptionMessageCodec.java:57)
    at io.vertx.core.eventbus.impl.codecs.ReplyExceptionMessageCodec.decodeFromWire(ReplyExceptionMessageCodec.java:23)
    at io.vertx.core.eventbus.impl.clustered.ClusteredMessage.decodeBody(ClusteredMessage.java:195)
    at io.vertx.core.eventbus.impl.clustered.ClusteredMessage.body(ClusteredMessage.java:100)
    at io.vertx.core.eventbus.impl.ReplyHandler.dispatch(ReplyHandler.java:89)
    at io.vertx.core.eventbus.impl.HandlerRegistration$InboundDeliveryContext.next(HandlerRegistration.java:163)
    at io.vertx.core.eventbus.impl.HandlerRegistration$InboundDeliveryContext.dispatch(HandlerRegistration.java:128)
    at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:107)
    at io.vertx.core.eventbus.impl.HandlerRegistration.dispatch(HandlerRegistration.java:104)
    at io.vertx.core.eventbus.impl.ReplyHandler.doReceive(ReplyHandler.java:75)
    at io.vertx.core.eventbus.impl.HandlerRegistration.lambda$receive$0(HandlerRegistration.java:54)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.base/java.lang.Thread.run(Thread.java:834)

13:43:29,489 ERROR (vert.x-eventloop-thread-1) [i.h.c.ControllerVerticle] 0000 Agent agent-two(2b7eb273-73ec-45cd-a727-0c1df9f69a4d) failed to initialize (RECIPIENT_FAILURE,1) io.netty.channel.StacklessClosedChannelException
    at io.vertx.core.eventbus.impl.codecs.ReplyExceptionMessageCodec.decodeFromWire(ReplyExceptionMessageCodec.java:57)
    at io.vertx.core.eventbus.impl.codecs.ReplyExceptionMessageCodec.decodeFromWire(ReplyExceptionMessageCodec.java:23)
    at io.vertx.core.eventbus.impl.clustered.ClusteredMessage.decodeBody(ClusteredMessage.java:195)
    at io.vertx.core.eventbus.impl.clustered.ClusteredMessage.body(ClusteredMessage.java:100)
    at io.vertx.core.eventbus.impl.ReplyHandler.dispatch(ReplyHandler.java:89)
    at io.vertx.core.eventbus.impl.HandlerRegistration$InboundDeliveryContext.next(HandlerRegistration.java:163)
    at io.vertx.core.eventbus.impl.HandlerRegistration$InboundDeliveryContext.dispatch(HandlerRegistration.java:128)
    at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:107)
    at io.vertx.core.eventbus.impl.HandlerRegistration.dispatch(HandlerRegistration.java:104)
    at io.vertx.core.eventbus.impl.ReplyHandler.doReceive(ReplyHandler.java:75)
    at io.vertx.core.eventbus.impl.HandlerRegistration.lambda$receive$0(HandlerRegistration.java:54)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.base/java.lang.Thread.run(Thread.java:834)
```

The log above can create "multiple guessing".

As a developer, I would like to see the root cause that was throw in the agent pod.
Example:

```
13:50:48,269 TRACE (vert.x-eventloop-thread-0) [s.o.i.c.h.i.t.n.ChannelFactory] Ignoring exception pinging configured servers [example-infinispan.hyperfoil.svc.cluster.local:11222] to establish a connection shaded.org.infinispan.client.hotrod.exceptions.TransportException:: io.netty.channel.StacklessClosedChannelException
	at shaded.org.infinispan.client.hotrod.impl.Util.rewrap(Util.java:84)
	at shaded.org.infinispan.client.hotrod.impl.Util.await(Util.java:57)
	at shaded.org.infinispan.client.hotrod.impl.transport.netty.ChannelFactory.pingServersIgnoreException(ChannelFactory.java:203)
	at shaded.org.infinispan.client.hotrod.impl.transport.netty.ChannelFactory.start(ChannelFactory.java:153)
	at shaded.org.infinispan.client.hotrod.RemoteCacheManager.actualStart(RemoteCacheManager.java:374)
	at shaded.org.infinispan.client.hotrod.RemoteCacheManager.start(RemoteCacheManager.java:334)
	at shaded.org.infinispan.client.hotrod.RemoteCacheManager.<init>(RemoteCacheManager.java:192)
	at shaded.org.infinispan.client.hotrod.RemoteCacheManager.<init>(RemoteCacheManager.java:149)
	at io.hyperfoil.hotrod.connection.HotRodRemoteCachePoolImpl.start(HotRodRemoteCachePoolImpl.java:43)
	at io.hyperfoil.hotrod.HotRodRunData.openConnections(HotRodRunData.java:55)
	at io.hyperfoil.core.impl.SimulationRunner.openConnections(SimulationRunner.java:146)
	at io.hyperfoil.clustering.AgentVerticle.initBenchmark(AgentVerticle.java:247)
	at io.hyperfoil.clustering.AgentVerticle.handleAgentControlMessage(AgentVerticle.java:117)
	at io.hyperfoil.clustering.AgentVerticle.lambda$start$0(AgentVerticle.java:80)
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:52)
	at io.vertx.core.impl.DuplicatedContext.emit(DuplicatedContext.java:194)
	at io.vertx.core.eventbus.impl.MessageConsumerImpl.dispatch(MessageConsumerImpl.java:177)
	at io.vertx.core.eventbus.impl.HandlerRegistration$InboundDeliveryContext.next(HandlerRegistration.java:163)
	at io.vertx.core.eventbus.impl.HandlerRegistration$InboundDeliveryContext.dispatch(HandlerRegistration.java:128)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:107)
	at io.vertx.core.eventbus.impl.HandlerRegistration.dispatch(HandlerRegistration.java:104)
	at io.vertx.core.eventbus.impl.MessageConsumerImpl.deliver(MessageConsumerImpl.java:183)
	at io.vertx.core.eventbus.impl.MessageConsumerImpl.doReceive(MessageConsumerImpl.java:168)
	at io.vertx.core.eventbus.impl.HandlerRegistration.lambda$receive$0(HandlerRegistration.java:54)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: io.netty.channel.StacklessClosedChannelException
	at io.netty.channel.AbstractChannel$AbstractUnsafe.ensureOpen(ChannelPromise)(Unknown Source)
```

**Comment by rvansa** [comment]
Ok, we can send the whole exception, not just the exception message. Also we should prevent agents from restarting.
