### ISSUE TITLE
Parsing exception message is not returned to client through rest api

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Hyperfoil#18]
If there is a parsing exception for a benchmark uploaded via rest api, the exception message is not returned to the client. 

Client side message
```
HTTP/1.1 500 Internal Server Error
content-length: 21

Internal Server Error
```

server side message

```
10:44:41,088 ERROR (vert.x-eventloop-thread-0) [i.v.e.w.i.RoutingContextImplBase] Unexpected exception in route java.lang.IllegalArgumentException: No initial sequences.
	at io.hyperfoil.api.config.ScenarioBuilder.build(ScenarioBuilder.java:100)
	at io.hyperfoil.api.config.PhaseBuilder$ConstantPerSec.buildPhase(PhaseBuilder.java:416)
	at io.hyperfoil.api.config.PhaseBuilder$ConstantPerSec.buildPhase(PhaseBuilder.java:392)
	at io.hyperfoil.api.config.PhaseBuilder.lambda$null$3(PhaseBuilder.java:157)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1492)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
...
```

The exception message should be returned to the client

**Comment by rvansa** [comment]
This is intentional - in general servers should not disclose stack traces to clients. I agree, though, that more details on the problem in parsing would be useful. Passing the stack trace in case of HF probably ain't a security risk, so it'd be the simplest solution.

Btw., the problem here should be reported as `BenchmarkDefinitionException`.

**Comment by johnaohara** [comment]
Agree, user should not see stack trace, but a `BenchmarkDefinitionException` that wraps the `No initial sequences.` would provide some useful feedback

**Comment by rvansa** [comment]
Looks like I've already handled this.
