### ISSUE TITLE
A lot of "java.lang.IllegalStateException: Too long header line" during run

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Hyperfoil#19]
During a benchmark run, I am seeing a lot of the exception below.

The dataset grows to 299 KB during the run, I suspect that we are quickly running out of buffer space for large result sets

```
13:11:28,084 WARN  (nioEventLoopGroup-2-1) [i.h.c.c.n.Http1xConnection] Exception in Http1xConnection{/127.0.0.1:38204 -> localhost/127.0.0.1:8080, size=1} java.lang.IllegalStateException: Too long header line.
	at io.hyperfoil.core.client.netty.Http1xRawBytesHandler.copyLastLine(Http1xRawBytesHandler.java:219)
	at io.hyperfoil.core.client.netty.Http1xRawBytesHandler.readChunks(Http1xRawBytesHandler.java:210)
	at io.hyperfoil.core.client.netty.Http1xRawBytesHandler.channelRead(Http1xRawBytesHandler.java:75)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by johnaohara** [comment]
Headers for request;
```
GET /fruits HTTP/1.1
host: localhost:8080
```
Response;

```
HTTP/1.1 200 OK
Connection: keep-alive
Transfer-Encoding: chunked
Content-Type: application/json
Date: Wed, 10 Apr 2019 12:16:44 GMT
```

**Comment by rvansa** [comment]
These are just headers; what are the actual chunks? Response body should contain
```
numberCRLF
somedata
numberCRLF
otherdata
0CRLF
```

**Comment by rvansa** [comment]
Addresed in 0a7ec8b292c448215b818bea17590e2ef0283bdb - reopen if you keep having any issues!
