### ISSUE TITLE
Do not use reflection to get fast UUIDs

### ISSUE THREAD

**Issue by aldettinger** [Hyperfoil/Hyperfoil#237]
When using the hyperfoil-maven-plugin with FastUUIDGenerator and Java 17. An error message is thrown:

```
Unable to make static java.lang.String 
java.lang.Long.fastUUID(long,long) accessible: module java.base does not
 "opens java.lang" to unnamed module @1bbebf8e
```

It's possible to workaround this issue by using `export MAVEN_OPTS="--add-opens java.base/java.lang=ALL-UNNAMED"`. However, `MAVEN_OPTS` seems to apply to all maven instances globally.

Linked to camel-quarkus issue https://github.com/apache/camel-quarkus/issues/4016.

**Comment by aldettinger** [comment]
The underlying stack trace is here:

```
14:48:11,469 ERROR (epollEventLoopGroup-2-1) [i.h.a.s.SequenceInstance] #0 phase operator, seq hello[0] failure invoking step randomUUID java.lang.ExceptionInInitializerError
	at io.hyperfoil.core.generators.RandomUUIDStep.invoke(RandomUUIDStep.java:28)
	at io.hyperfoil.api.session.SequenceInstance.progress(SequenceInstance.java:33)
	at io.hyperfoil.core.session.SessionImpl.runSession(SessionImpl.java:275)
	at io.hyperfoil.core.session.SessionImpl.call(SessionImpl.java:228)
	at io.hyperfoil.core.session.SessionImpl.deferredStart(SessionImpl.java:356)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:96)
	at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:106)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make static java.lang.String java.lang.Long.fastUUID(long,long) accessible: module java.base does not "opens java.lang" to unnamed module @38499139
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	at io.hyperfoil.core.util.LongFastUUID.<clinit>(LongFastUUID.java:23)
	... 14 more

14:48:11,470 ERROR (epollEventLoopGroup-2-1) [i.h.c.s.SessionImpl] #0 Failing phase operator java.lang.ExceptionInInitializerError
	at io.hyperfoil.core.generators.RandomUUIDStep.invoke(RandomUUIDStep.java:28)
	at io.hyperfoil.api.session.SequenceInstance.progress(SequenceInstance.java:33)
	at io.hyperfoil.core.session.SessionImpl.runSession(SessionImpl.java:275)
	at io.hyperfoil.core.session.SessionImpl.call(SessionImpl.java:228)
	at io.hyperfoil.core.session.SessionImpl.deferredStart(SessionImpl.java:356)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:96)
	at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:106)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make static java.lang.String java.lang.Long.fastUUID(long,long) accessible: module java.base does not "opens java.lang" to unnamed module @38499139
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	at io.hyperfoil.core.util.LongFastUUID.<clinit>(LongFastUUID.java:23)
	... 14 more
```

The offending code looks to be located [there](https://github.com/Hyperfoil/Hyperfoil/blob/master/core/src/main/java/io/hyperfoil/core/util/LongFastUUID.java#L19..#L23).

**Comment by rvansa** [comment]
Okay, I thought it might cause trouble with newer JDKs. I'll implement it in a regular way.

**Comment by rvansa** [comment]
@aldettinger Pushed, could you try if master works better for you?

**Comment by aldettinger** [comment]
Well done @rvansa, the implementation looks good. It's working locally against hyperfoil-maven-plugin:0.22-SNAPSHOT :+1: 

The produced GUID looks fine:
```
2022-08-23 10:36:06,066 INFO  [route1] (executor-thread-0) Body: Hello b1e14722-f0a4-84e7-77a9-97c43857504b
2022-08-23 10:36:06,067 INFO  [route1] (executor-thread-0) Body: Hello f52023df-46dd-962c-be24-ae89fcbae556
2022-08-23 10:36:06,068 INFO  [route1] (executor-thread-0) Body: Hello 549c3445-5dd7-0fd9-aa49-1ddd3cedeb3c
2022-08-23 10:36:06,069 INFO  [route1] (executor-thread-0) Body: Hello f73d224a-c395-0dc6-b0b7-75bc472d51ee
2022-08-23 10:36:06,070 INFO  [route1] (executor-thread-0) Body: Hello 4bce81ce-d805-2158-8154-eb60dabba313
2022-08-23 10:36:06,071 INFO  [route1] (executor-thread-0) Body: Hello 3674d83d-a807-d315-7609-694b97663c83
2022-08-23 10:36:06,072 INFO  [route1] (executor-thread-0) Body: Hello a5d27b23-ad8c-101b-a3b1-6377fe7931db
2022-08-23 10:36:06,073 INFO  [route1] (executor-thread-0) Body: Hello d7c13a82-779e-c7fb-eb8f-c4a22fde9985
2022-08-23 10:36:06,074 INFO  [route1] (executor-thread-0) Body: Hello b3ec9528-a2ce-4a10-b262-458d748ea503
2022-08-23 10:36:06,075 INFO  [route1] (executor-thread-0) Body: Hello 39a2e1fc-bc11-430e-e105-14a42793a697
2022-08-23 10:36:06,076 INFO  [route1] (executor-thread-0) Body: Hello 8aaa9ee5-e0f5-efb2-63e7-3c37e7a06dc0
2022-08-23 10:36:06,077 INFO  [route1] (executor-thread-0) Body: Hello 9dac4aae-05f7-a6b5-a002-9f853fe4bbbd
2022-08-23 10:36:06,078 INFO  [route1] (executor-thread-0) Body: Hello de7d0294-cad7-9bf6-4887-2ad137666890
2022-08-23 10:36:06,078 INFO  [route1] (executor-thread-0) Body: Hello 227155b6-328c-b12e-ac53-a2fbb98b5d4c
2022-08-23 10:36:06,079 INFO  [route1] (executor-thread-0) Body: Hello 0996b2d5-decc-281b-7363-4117be6184f4
2022-08-23 10:36:06,080 INFO  [route1] (executor-thread-0) Body: Hello 0edf81ae-eaa8-a60c-902a-4db4e50109a4
2022-08-23 10:36:06,081 INFO  [route1] (executor-thread-0) Body: Hello b7183d21-c201-4304-d728-9b58ae067844
```

From my point of view the issue could be closed ? Well done :+1:

**Comment by rvansa** [comment]
@aldettinger Thanks for the confirmation, closing.
