### ISSUE TITLE
NotSerializableException thrown when using `timestamp` in OpenShift

### ISSUE THREAD

**Issue by sutaakar** [Hyperfoil/Hyperfoil#248]
Using `timestamp` step in Hyperfoil deployed as controller with agents causes NotSerializableException to be thrown.

Environment:
Hyperfoil operator 0.15.1

Reproducer:
Deploy latest Hyperfoil operator in OpenShift
Create Hyperfoil CR with default values.
Upload benchmark:
```
name: single-request
agents:
- driver01
- driver02
http:
  host: http://hyperfoil.io
phases:
- example:
    atOnce:
      users: 1
      scenario:
      - test:
        - timestamp:
            toVar: submitted_at
            pattern: "yyyy-MM-dd'T'HH:mm:ss.SSSSSSZ"
```
Start the benchmark.
Check `hyperfoil-controller` pod log. It contains this error:
```
12:20:15,392 INFO  (vert.x-worker-thread-9) [i.h.c.u.PersistenceUtil] Stored benchmark 'single-request' in /var/hyperfoil/benchmark/single-request.yaml
12:20:19,467 INFO  (vert.x-eventloop-thread-1) [i.h.c.u.PersistenceUtil] Stored benchmark 'single-request' in /var/hyperfoil/run/0002/single-request.yaml
12:20:19,467 INFO  (vert.x-eventloop-thread-1) [i.h.c.ControllerVerticle] Starting agents for run 0002
12:20:27,236 INFO  (vert.x-eventloop-thread-1) [i.h.c.ControllerVerticle] Starting benchmark single-request - run 0002
java.io.NotSerializableException: io.hyperfoil.core.steps.TimestampStep$Builder
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1175)
	at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1543)
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1500)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1423)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1169)
	at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1543)
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1500)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1423)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1169)
	at java.base/java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1369)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1165)
	at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1543)
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1500)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1423)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1169)
	at java.base/java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1369)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1165)
	at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1543)
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1500)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1423)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1169)
	at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1543)
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1500)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1423)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1169)
	at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:345)
	at java.base/java.util.ArrayList.writeObject(ArrayList.java:897)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1016)
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1487)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1423)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1169)
	at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1543)
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1500)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1423)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1169)
	at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1543)
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1500)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1423)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1169)
	at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:345)
	at io.hyperfoil.clustering.messages.ObjectCodec.encodeToWire(ObjectCodec.java:46)
	at io.vertx.core.eventbus.impl.clustered.ClusteredMessage.writeBody(ClusteredMessage.java:241)
	at io.vertx.core.eventbus.impl.clustered.ClusteredMessage.encodeToWire(ClusteredMessage.java:131)
	at io.vertx.core.eventbus.impl.clustered.ConnectionHolder.writeMessage(ConnectionHolder.java:75)
	at io.vertx.core.eventbus.impl.clustered.ClusteredEventBus.sendRemote(ClusteredEventBus.java:356)
	at io.vertx.core.eventbus.impl.clustered.ClusteredEventBus.sendToNode(ClusteredEventBus.java:307)
	at io.vertx.core.eventbus.impl.clustered.ClusteredEventBus.lambda$sendOrPub$4(ClusteredEventBus.java:181)
	at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
	at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:87)
	at io.vertx.core.impl.DuplicatedContext.execute(DuplicatedContext.java:179)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:51)
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
	at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23)
	at io.vertx.core.impl.future.PromiseImpl.onSuccess(PromiseImpl.java:49)
	at io.vertx.core.impl.future.FutureImpl$ListenerArray.onSuccess(FutureImpl.java:262)
	at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
12:20:27,267 ERROR (vert.x-eventloop-thread-1) [i.h.c.ControllerVerticle] 0002 Agent driver01(0d09c63b-fe67-4fc9-99a1-8be88d1718b1) failed to initialize
12:20:27,268 ERROR (vert.x-eventloop-thread-1) [i.h.c.ControllerVerticle] Failure thrown on the controller (this node): (RECIPIENT_FAILURE,1) 193 + 4 > 193
	at io.vertx.core.eventbus.impl.codecs.ReplyExceptionMessageCodec.decodeFromWire(ReplyExceptionMessageCodec.java:57)
	at io.vertx.core.eventbus.impl.codecs.ReplyExceptionMessageCodec.decodeFromWire(ReplyExceptionMessageCodec.java:23)
	at io.vertx.core.eventbus.impl.clustered.ClusteredMessage.decodeBody(ClusteredMessage.java:195)
	at io.vertx.core.eventbus.impl.clustered.ClusteredMessage.body(ClusteredMessage.java:100)
	at io.vertx.core.eventbus.impl.ReplyHandler.dispatch(ReplyHandler.java:93)
	at io.vertx.core.eventbus.impl.HandlerRegistration$InboundDeliveryContext.execute(HandlerRegistration.java:137)
	at io.vertx.core.eventbus.impl.DeliveryContextBase.next(DeliveryContextBase.java:72)
	at io.vertx.core.eventbus.impl.DeliveryContextBase.dispatch(DeliveryContextBase.java:43)
	at io.vertx.core.eventbus.impl.HandlerRegistration.dispatch(HandlerRegistration.java:98)
	at io.vertx.core.eventbus.impl.ReplyHandler.doReceive(ReplyHandler.java:81)
	at io.vertx.core.eventbus.impl.HandlerRegistration.lambda$receive$0(HandlerRegistration.java:49)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

Expected outcome:
Benchmark with timestamp step is executed without errors, timestamp is stored in variable.

**Comment by rvansa** [comment]
Stupid mistake, I've pushed a fix for that. Thanks for reporting.

**Comment by sutaakar** [comment]
@rvansa unfortunately I have reproduced the issue in 0.23 version too.
It can be reproduced by running standalone instance (./bin/standalone.sh) and uploading the scenario with timestable using cli.

**Comment by rvansa** [comment]
@sutaakar Damned, I should have tested that. A new thing to learn: when you create anonymous inner class like `new MyInterface() {}` from a non-static method it still captures the outer class reference :-/

**Comment by rvansa** [comment]
Okay, not entirely new... https://github.com/Hyperfoil/Hyperfoil/blob/2d12deeee24bd659735d58a0a630fcd745b81687/core/src/main/java/io/hyperfoil/core/steps/RestartSequenceStep.java#L18

**Comment by rvansa** [comment]
eede8e2cc58de21fa26d5c1e192fdec46f903a06
