### ISSUE TITLE
Stacktrace on macOS, bad initial impression

### ISSUE THREAD

**Issue by rsvoboda** [Hyperfoil/Hyperfoil#249]
Stacktrace on macOS, bad initial impression

Reproducer:
 - follow https://hyperfoil.io/quickstart/quickstart1.html on macOS

```
~/Downloads/hyperfoil-0.23> bin/cli.sh
19:39:04,049 ERROR (main) [i.n.r.d.DnsServerAddressStreamProviders] Unable to load io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider, fallback to system defaults. This may result in incorrect DNS resolutions on MacOS. java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at io.netty.resolver.dns.DnsServerAddressStreamProviders.<clinit>(DnsServerAddressStreamProviders.java:64)
	at io.netty.resolver.dns.DnsNameResolverBuilder.<init>(DnsNameResolverBuilder.java:60)
	at io.vertx.core.impl.resolver.DnsResolverProvider.<init>(DnsResolverProvider.java:124)
	at io.vertx.core.spi.resolver.ResolverProvider.factory(ResolverProvider.java:39)
	at io.vertx.core.impl.AddressResolver.<init>(AddressResolver.java:76)
	at io.vertx.core.impl.VertxImpl.<init>(VertxImpl.java:181)
	at io.vertx.core.impl.VertxBuilder.vertx(VertxBuilder.java:225)
	at io.vertx.core.Vertx.vertx(Vertx.java:86)
	at io.vertx.core.Vertx.vertx(Vertx.java:76)
	at io.hyperfoil.cli.context.HyperfoilCliContext.<init>(HyperfoilCliContext.java:73)
	at io.hyperfoil.cli.HyperfoilCli.run(HyperfoilCli.java:103)
	at io.hyperfoil.cli.HyperfoilCli.main(HyperfoilCli.java:99)
Caused by: java.lang.UnsatisfiedLinkError: failed to load the required native library
	at io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider.ensureAvailability(MacOSDnsServerAddressStreamProvider.java:110)
	at io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider.<init>(MacOSDnsServerAddressStreamProvider.java:120)
	... 16 more
Caused by: java.lang.UnsatisfiedLinkError: could not load a native library: netty_resolver_dns_native_macos_x86_64
	at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:224)
	at io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider.loadNativeLibrary(MacOSDnsServerAddressStreamProvider.java:92)
	at io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider.<clinit>(MacOSDnsServerAddressStreamProvider.java:77)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at io.netty.resolver.dns.DnsServerAddressStreamProviders$1.run(DnsServerAddressStreamProviders.java:50)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at io.netty.resolver.dns.DnsServerAddressStreamProviders.<clinit>(DnsServerAddressStreamProviders.java:46)
	... 11 more
	Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: netty_resolver_dns_native_macos
		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:224)
		at io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider.loadNativeLibrary(MacOSDnsServerAddressStreamProvider.java:95)
		... 17 more
	Caused by: java.io.FileNotFoundException: META-INF/native/libnetty_resolver_dns_native_macos.jnilib
		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:166)
		... 18 more
		Suppressed: java.lang.UnsatisfiedLinkError: no netty_resolver_dns_native_macos in java.library.path: [/Users/rsvoboda/Library/Java/Extensions, /Library/Java/Extensions, /Network/Library/Java/Extensions, /System/Library/Java/Extensions, /usr/lib/java, .]
			at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
			at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
			at java.base/java.lang.System.loadLibrary(System.java:1871)
			at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
			at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:376)
			at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:146)
			... 18 more
			Suppressed: java.lang.UnsatisfiedLinkError: no netty_resolver_dns_native_macos in java.library.path: [/Users/rsvoboda/Library/Java/Extensions, /Library/Java/Extensions, /Network/Library/Java/Extensions, /System/Library/Java/Extensions, /usr/lib/java, .]
				at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
				at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
				at java.base/java.lang.System.loadLibrary(System.java:1871)
				at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
				at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
				at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
				at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
				at java.base/java.lang.reflect.Method.invoke(Method.java:566)
				at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:410)
				at java.base/java.security.AccessController.doPrivileged(Native Method)
				at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:402)
				at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:368)
				... 19 more
Caused by: java.io.FileNotFoundException: META-INF/native/libnetty_resolver_dns_native_macos_x86_64.jnilib
	at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:166)
	... 18 more
	Suppressed: java.lang.UnsatisfiedLinkError: no netty_resolver_dns_native_macos_x86_64 in java.library.path: [/Users/rsvoboda/Library/Java/Extensions, /Library/Java/Extensions, /Network/Library/Java/Extensions, /System/Library/Java/Extensions, /usr/lib/java, .]
		at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
		at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
		at java.base/java.lang.System.loadLibrary(System.java:1871)
		at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
		at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:376)
		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:146)
		... 18 more
		Suppressed: java.lang.UnsatisfiedLinkError: no netty_resolver_dns_native_macos_x86_64 in java.library.path: [/Users/rsvoboda/Library/Java/Extensions, /Library/Java/Extensions, /Network/Library/Java/Extensions, /System/Library/Java/Extensions, /usr/lib/java, .]
			at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
			at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
			at java.base/java.lang.System.loadLibrary(System.java:1871)
			at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
			at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
			at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
			at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
			at java.base/java.lang.reflect.Method.invoke(Method.java:566)
			at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:410)
			at java.base/java.security.AccessController.doPrivileged(Native Method)
			at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:402)
			at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:368)
			... 19 more
			
```

**Comment by rsvoboda** [comment]
Tool works, but the errors are discouraging

**Comment by rvansa** [comment]
Thanks, looks like there's just a dependency missing, I'll add it. Sadly it's not possible to test all niché OS without extra HW. TBH I don't know if anyone ever tried Windows either.

**Comment by johnaohara** [comment]
@rsvoboda is this macOS on intel hardware? on m2 it starts without error;

```
johara@johara-mac hyperfoil-0.23 % ll
total 0
drwxr-xr-x   8 johara  staff   256B 31 Oct 12:29 .
drwxr-xr-x   4 johara  staff   128B 15 Nov 08:40 ..
drwxr-xr-x   9 johara  staff   288B 31 Oct 12:29 bin
drwxr-xr-x   3 johara  staff    96B 31 Oct 12:29 docs
drwxr-xr-x  14 johara  staff   448B 31 Oct 12:29 examples
drwxr-xr-x   3 johara  staff    96B 31 Oct 12:29 extensions
drwxr-xr-x  92 johara  staff   2.9K 31 Oct 12:29 lib
drwxr-xr-x   3 johara  staff    96B 31 Oct 12:29 templates
johara@johara-mac hyperfoil-0.23 % bin/cli.sh

[hyperfoil]$ 
[hyperfoil]$ start-local
Starting controller in default directory (/tmp/hyperfoil)
Controller started, listening on 127.0.0.1:53756
Connecting to the controller...
Connected to 127.0.0.1:53756!
[hyperfoil@in-vm]$
```

**Comment by rsvoboda** [comment]
I have Intel based MBP

**Comment by rsvoboda** [comment]
```
 ~/tmp/Hyperfoil - master > distribution/target/distribution/bin/cli.sh
[hyperfoil]$
```
No errors are present when using main

**Comment by rsvoboda** [comment]
Fixed by https://github.com/Hyperfoil/Hyperfoil/commit/914f159b7061e21ecaa3c8ad1152cd9ce4e2571b
