### ISSUE TITLE
Error when trying to upload the `yml` file

### ISSUE THREAD

**Issue by helio-frota** [Hyperfoil/Hyperfoil#271]
Hi folks, I'm using the latest version and maybe I'm missing something when trying to upload the `yml` file.

```console
[hyperfoil@in-vm]$ version
Server: 0.24, 8fc3bb798b1964f40acdca3f2c3e283ca5e8b98d
Client: 0.24, 8fc3bb798b1964f40acdca3f2c3e283ca5e8b98d
```

```console
[hyperfoil@in-vm]$ upload ../otel.hf.yml
ERROR: Cannot invoke "String.length()" because "str" is null
Use --print-stack-trace to display the whole stack trace of this error.
Unknown error.
[hyperfoil@in-vm]$ upload /home/heliofrota/code/hyperfoil-test/otel.hf.yml
ERROR: Cannot invoke "String.length()" because "str" is null
Use --print-stack-trace to display the whole stack trace of this error.
Unknown error.
[hyperfoil@in-vm]$ upload /home/heliofrota/code/hyperfoil-test/otel.hf.yml --print-stack-trace
ERROR: Cannot invoke "String.length()" because "str" is null
	at java.base/java.lang.AbstractStringBuilder.<init>(AbstractStringBuilder.java:105)
	at java.base/java.lang.StringBuilder.<init>(StringBuilder.java:131)
	at io.hyperfoil.http.config.HttpPluginBuilder.compareAuthorities(HttpPluginBuilder.java:123)
	at io.hyperfoil.http.config.HttpPluginBuilder.lambda$isValidAuthority$2(HttpPluginBuilder.java:112)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.ReduceOps$5.evaluateSequential(ReduceOps.java:258)
	at java.base/java.util.stream.ReduceOps$5.evaluateSequential(ReduceOps.java:248)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.count(ReferencePipeline.java:709)
	at io.hyperfoil.http.config.HttpPluginBuilder.isValidAuthority(HttpPluginBuilder.java:113)
	at io.hyperfoil.http.config.HttpPluginBuilder.validateAuthority(HttpPluginBuilder.java:106)
	at io.hyperfoil.http.steps.HttpRequestStepBuilder.build(HttpRequestStepBuilder.java:615)
	at io.hyperfoil.api.config.BaseSequenceBuilder.lambda$buildSteps$2(BaseSequenceBuilder.java:109)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.hyperfoil.api.config.BaseSequenceBuilder.buildSteps(BaseSequenceBuilder.java:112)
	at io.hyperfoil.api.config.SequenceBuilder.build(SequenceBuilder.java:86)
	at io.hyperfoil.api.config.ScenarioBuilder.build(ScenarioBuilder.java:133)
	at io.hyperfoil.api.config.PhaseBuilder.buildPhase(PhaseBuilder.java:172)
	at io.hyperfoil.api.config.PhaseBuilder.lambda$build$4(PhaseBuilder.java:147)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180)
	at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104)
	at java.base/java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:711)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.hyperfoil.api.config.PhaseBuilder.build(PhaseBuilder.java:148)
	at io.hyperfoil.api.config.BenchmarkBuilder.lambda$build$1(BenchmarkBuilder.java:148)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.hyperfoil.api.config.BenchmarkBuilder.build(BenchmarkBuilder.java:148)
	at io.hyperfoil.core.parser.BenchmarkParser.buildBenchmark(BenchmarkParser.java:91)
	at io.hyperfoil.cli.commands.BaseUploadCommand.loadBenchmarkSource(BaseUploadCommand.java:48)
	at io.hyperfoil.cli.commands.Upload.uploadFromFile(Upload.java:82)
	at io.hyperfoil.cli.commands.Upload.execute(Upload.java:48)
	at io.hyperfoil.cli.commands.Upload.execute(Upload.java:25)
	at org.aesh.command.impl.operator.EndOperator.execute(EndOperator.java:41)
	at org.aesh.command.impl.Executions$ExecutionImpl.execute(Executions.java:222)
	at org.aesh.readline.Process.run(Process.java:80)
Unknown error.
[hyperfoil@in-vm]$
```

After copy the `otel.hf.yml` file to `/tmp/hyperfoil`  

```console
…perfoil-test git:(main)   cp otel.hf.yml /tmp/hyperfoil/
➜  hyperfoil-test git:(main) ✗ cd /tmp/hyperfoil/
➜  hyperfoil ls
benchmark/  hooks/  hyperfoil.local.log  otel.hf.yml
```

I saw a different error output:

```console
[hyperfoil@in-vm]$ upload otel.hf.yml --print-stack-trace
ERROR: otel.hf.yml
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:380)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:432)
	at java.base/java.nio.file.Files.readAllBytes(Files.java:3288)
	at java.base/java.nio.file.Files.readString(Files.java:3366)
	at java.base/java.nio.file.Files.readString(Files.java:3325)
	at io.hyperfoil.cli.commands.Upload.uploadFromFile(Upload.java:71)
	at io.hyperfoil.cli.commands.Upload.execute(Upload.java:48)
	at io.hyperfoil.cli.commands.Upload.execute(Upload.java:25)
	at org.aesh.command.impl.operator.EndOperator.execute(EndOperator.java:41)
	at org.aesh.command.impl.Executions$ExecutionImpl.execute(Executions.java:222)
	at org.aesh.readline.Process.run(Process.java:80)
Failed to load the benchmark.
```

Here is the `yml` I'm using https://github.com/obs-nebula/hyperfoil-test/blob/main/otel.hf.yml

thanks

**Comment by helio-frota** [comment]
That is something wrong with my `yml` file.

I changed the `yml` file to (almost nothing)

```yml
name: otel-disabled
http:
 host: http://localhost:8080
 sharedConnections: 80
```

The got this result:

```
[hyperfoil@in-vm]$ upload ../otel.hf.yml
Loaded benchmark otel-disabled, uploading...
... done.
```

**Comment by helio-frota** [comment]
I suspect that is because I forgot to add `authority: ` attribute.

After take a look on this: https://github.com/Hyperfoil/vehicle-market/blob/master/benchmarks/vehicle-market-1.hf.yaml

The test is working now :+1: 

![2023-01-27_08-06](https://user-images.githubusercontent.com/6443576/215071875-1659574e-51b9-4fce-829d-4add78cc51e5.png)

**Comment by johnaohara** [comment]
Hi @helio-frota, thanks for reporting this issue. 

I am going to re-open as I think the error message reported to users could be more intuitive than a stack trace

**Comment by helio-frota** [comment]
@johnaohara sorry I closed by impulse.  

>  I think the error message reported to users could be more intuitive than a stack trace

+1

**Comment by johnaohara** [comment]
no problem

**Comment by jesperpedersen** [comment]
We need to document the format, and make sure that required fields are present

**Comment by jesperpedersen** [comment]
Maybe it is a regression in `vertx 4.3.6` patch with the dependencies - so switching to NIO is likely a good starting point
