### ISSUE TITLE
HttpRequestTest: Failure

### ISSUE THREAD

**Issue by jesperpedersen** [Hyperfoil/Hyperfoil#280]
```
Error:  io.hyperfoil.http.steps.HttpRequestTest.testStatusValidator  Time elapsed: 0.101 s  <<< ERROR!
java.lang.NullPointerException
	at io.hyperfoil.http.statistics.HttpStats.get(HttpStats.java:54)
	at io.hyperfoil.http.steps.HttpRequestTest.testStatusValidator(HttpRequestTest.java:170)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.vertx.ext.unit.junit.VertxUnitRunner.invokeTestMethod(VertxUnitRunner.java:93)
	at io.vertx.ext.unit.junit.VertxUnitRunner.lambda$invokeExplosively$0(VertxUnitRunner.java:114)
	at io.vertx.ext.unit.impl.TestContextImpl.run(TestContextImpl.java:90)
	at io.vertx.ext.unit.junit.VertxUnitRunner.invokeExplosively(VertxUnitRunner.java:130)
```

**Comment by lampajr** [comment]
I think this issue is no longer valid as the test looks working, closing the issue.
