### ISSUE TITLE
[s390x] Benchmark is failing in Hyperfoil in OCP cluster

### ISSUE THREAD

**Issue by titlisgupta** [Hyperfoil/Hyperfoil#316]
Environment:

OCP : 4.13

Issue:

We are able to run Hyperfoil in a s390x OpenShift cluster. We have created s390x specific images for hyperfoil and the hyperfoil operator. We are successfully able to install the operator and run a hyperfoil instance but when I am trying  to run any benchmark its failing. The hyperfoil agent is running but when we are running benchmark it's erroring out.

Benchmark:

```
name: k8s-hello-world
agents:
  agent-one:
    image: quay.io/ibm-z-performance/hyperfoil:latest
http:
  host: http://productpage-bookinfo.apps.a314lp45ocp.lnxne.boe
  sharedConnections: 10
duration: 5s
usersPerSec: 5
scenario:
- test:
  - httpRequest:
      GET: /
```
Error:

<img width="1537" alt="image" src="https://github.com/Hyperfoil/Hyperfoil/assets/8019314/27663785-76dc-4a0e-8fa5-81f65d646c22">

Log of the agent pod:

```
[root@a3elp45 bookinfo]# oc logs pod/agent-0000-agent-one 
13:55:06,809 INFO  (main) [i.h.Hyperfoil] Java: Red Hat, Inc. OpenJDK 64-Bit Server VM 11.0.20 11.0.20+8-LTS (/usr/lib/jvm/java-11-openjdk-11.0.20.0.8-3.el8.s390x), CWD /home/jboss
13:55:06,813 INFO  (main) [i.h.Hyperfoil] Hyperfoil: 0.26-SNAPSHOT (5b0270aa95d8bacd262300a467bc170d4dc2c194)
13:55:06,813 INFO  (main) [i.h.Hyperfoil]            DISTRIBUTION:  /deployment
13:55:06,816 INFO  (main) [i.h.Hyperfoil]            ROOT_DIR:      /tmp/hyperfoil
13:55:06,816 INFO  (main) [i.h.Hyperfoil]            BENCHMARK_DIR: /tmp/hyperfoil/benchmark
13:55:06,816 INFO  (main) [i.h.Hyperfoil]            RUN_DIR:       /tmp/hyperfoil/run
13:55:06,817 INFO  (main) [i.h.Hyperfoil]            HOOKS_DIR:     /tmp/hyperfoil/hooks
13:55:06,818 INFO  (main) [i.h.Hyperfoil] Starting Vert.x...
13:55:06,837 INFO  (main) [i.h.Hyperfoil] Agent must choose NIC with best subnet match to controller (10-128-2-151.hyperfoil.hyperfoil.svc.cluster.local/10.128.2.151), available IPs: [/10.128.2.155] (loopback is ignored)
13:55:06,838 INFO  (main) [i.h.Hyperfoil] Using host name agent-0000-agent-one/10.128.2.155
13:55:07,406 WARN  (main) [o.i.CONFIG] ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
13:55:07,751 WARN  (main) [o.j.s.Configurator] JGRP000014: STABLE.stability_delay has been deprecated: always 0
13:55:07,780 INFO  (main) [i.h.HyperfoilChannelLookup] Connecting to controller 10.128.2.151:7800 (10.128.2.151:7800)
13:55:07,782 INFO  (main) [i.h.HyperfoilChannelLookup] Using 10.128.2.155:7800 as clustering address
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
SLF4J: Ignoring binding found at [jar:file:/deployment/lib/log4j-slf4j-impl-2.19.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See https://www.slf4j.org/codes.html#ignoredBindings for an explanation.
13:55:09,108 INFO  (vert.x-eventloop-thread-0) [i.h.Hyperfoil] Deploying AgentVerticle...
13:55:09,125 INFO  (vert.x-eventloop-thread-0) [i.h.Hyperfoil] AgentVerticle deployed.
13:55:09,136 INFO  (jgroups-4,agent-0000-agent-one-7069) [o.j.threads] JBoss Threads version 3.5.0.Final
13:55:10,277 INFO  (vert.x-eventloop-thread-2) [i.h.c.AgentVerticle] 9f4d8f4d-a2be-4e2e-9bba-b4099d95c0f9 Got reply from controller.
13:55:10,339 INFO  (vert.x-eventloop-thread-2) [i.h.c.AgentVerticle] Initializing agent
13:55:10,379 INFO  (vert.x-eventloop-thread-2) [i.h.h.c.HttpClientPoolImpl] Allocating 10 connections (max 10, buffer 0) in 1 executors to http://productpage-bookinfo.apps.a314lp45ocp.lnxne.boe:80
13:58:57,381 ERROR (jitter-watchdog) [i.h.c.i.SimulationRunner] 13:58:57.381 | Jitter watchdog was not invoked for 110 ms (threshold is 100 ms); please check your GC settings.
13:58:57,510 ERROR (jitter-watchdog) [i.h.c.i.SimulationRunner] 13:58:57.509 | Jitter watchdog was not invoked for 129 ms (threshold is 100 ms); please check your GC settings.
14:00:57,720 ERROR (jitter-watchdog) [i.h.c.i.SimulationRunner] 14:00:57.719 | Jitter watchdog was not invoked for 118 ms (threshold is 100 ms); please check your GC settings.

```
Upon checking the agent manifest we found out the resource of the agent pod is not allocated properly. 

```
containers:
    - resources:
        requests:
          cpu: '0'
```

The vehicle-market application is not running in our cluster, so I have deployed a simple application. I am able to ping the url from inside the agent pod.

```
sh-4.4$ curl -v http://productpage-bookinfo.apps.a314lp45ocp.lnxne.boe/
* Rebuilt URL to: http://productpage-bookinfo.apps.a314lp45ocp.lnxne.boe/
*   Trying 192.168.122.28...
* TCP_NODELAY set
* Connected to productpage-bookinfo.apps.a314lp45ocp.lnxne.boe (192.168.122.28) port 80 (#0)
> GET / HTTP/1.1
> Host: productpage-bookinfo.apps.a314lp45ocp.lnxne.boe
> User-Agent: curl/7.61.1
> Accept: */*
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< content-type: text/html; charset=utf-8
< content-length: 1683
< server: Werkzeug/0.15.5 Python/3.7.7
< date: Thu, 26 Oct 2023 14:02:15 GMT
< set-cookie: 3b8dae5ccb368f22c1603c4dd00d1534=0b7631005ae9c501dfeacd43998b9b5d; path=/; HttpOnly
< cache-control: private
* HTTP/1.0 connection set to keep alive!
< connection: keep-alive
< 
<!DOCTYPE html>
<html>
  <head>
    <title>Simple Bookstore App</title>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="static/bootstrap/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="static/bootstrap/css/bootstrap-theme.min.css">

  </head>
  <body>
    
    
<p>
    <h3>Hello! This is a simple bookstore application consisting of three services as shown below</h3>
</p>

<table class="table table-condensed table-bordered table-hover"><tr><th>name</th><td>http://details:9080</td></tr><tr><th>endpoint</th><td>details</td></tr><tr><th>children</th><td><table class="table table-condensed table-bordered table-hover"><tr><th>name</th><th>endpoint</th><th>children</th></tr><tr><td>http://details:9080</td><td>details</td><td></td></tr><tr><td>http://reviews:9080</td><td>reviews</td><td><table class="table table-condensed table-bordered table-hover"><tr><th>name</th><th>endpoint</th><th>children</th></tr><tr><td>http://ratings:9080</td><td>ratings</td><td></td></tr></table></td></tr></table></td></tr></table>

<p>
    <h4>Click on one of the links below to auto generate a request to the backend as a real user or a tester
    </h4>
</p>
<p><a href="/productpage?u=normal">Normal user</a></p>
<p><a href="/productpage?u=test">Test user</a></p>


    
<!-- Latest compiled and minified JavaScript -->
<script src="static/jquery.min.js"></script>

<!-- Latest compiled and minified JavaScript -->
<script src="static/bootstrap/js/bootstrap.min.js"></script>

  </body>
</html>
* Connection #0 to host productpage-bookinfo.apps.a314lp45ocp.lnxne.boe left intact

```

**Comment by titlisgupta** [comment]
I am able to set the resource in pod from benchmark. I had to modify the code to accept cpu request, provision for memory request was already there. Unfortunately the error is still same. Another observation, the benchmark is failing even before the agent pod is up.

Benchmark:
```
name: k8s-hello-world
agents:
  agent-one:
    image: quay.io/ibm-z-performance/hyperfoil:latest
    pod-cpu: "500m"
    pod-memory: "2Gi"
http:
  host: http://productpage-bookinfo.apps.a314lp45ocp.lnxne.boe
  sharedConnections: 5
  addresses:
  - 192.168.79.24
  - 192.168.79.25
duration: 5s
usersPerSec: 5
scenario:
- test:
  - httpRequest:
      GET: /
      
  ```
Agent Pod:

```
containers:
    - resources:
        requests:
          cpu: 500m
          memory: 2Gi
      terminationMessagePath: /dev/termination-log
      name: hyperfoil-agent
    
```

**Comment by titlisgupta** [comment]
This is the maximum resource we can allocate to the agent in current cluster. Do you think we will need more CPU for it? If yes can you suggest how much should be sufficient?

Agent:

```
Requests:
      cpu:        2900m
      memory:     4Gi
```
Log:
```
[root@a3elp45 ~]# oc logs agent-0008-agent-one  
15:17:49,994 INFO  (main) [i.h.Hyperfoil] Java: Red Hat, Inc. OpenJDK 64-Bit Server VM 11.0.21 11.0.21+9-LTS (/usr/lib/jvm/java-11-openjdk-11.0.21.0.9-2.el8.s390x), CWD /home/jboss
15:17:49,998 INFO  (main) [i.h.Hyperfoil] Hyperfoil: 0.26-SNAPSHOT (91021e2d8fc4d6671a0ceb4629661f25751fd1ba)
15:17:49,998 INFO  (main) [i.h.Hyperfoil]            DISTRIBUTION:  /deployment
15:17:50,000 INFO  (main) [i.h.Hyperfoil]            ROOT_DIR:      /tmp/hyperfoil
15:17:50,000 INFO  (main) [i.h.Hyperfoil]            BENCHMARK_DIR: /tmp/hyperfoil/benchmark
15:17:50,000 INFO  (main) [i.h.Hyperfoil]            RUN_DIR:       /tmp/hyperfoil/run
15:17:50,000 INFO  (main) [i.h.Hyperfoil]            HOOKS_DIR:     /tmp/hyperfoil/hooks
15:17:50,002 INFO  (main) [i.h.Hyperfoil] Starting Vert.x...
15:17:50,018 INFO  (main) [i.h.Hyperfoil] Agent must choose NIC with best subnet match to controller (10-128-2-36.hyperfoil-cluster.hyperfoil.svc.cluster.local/10.128.2.36), available IPs: [/10.128.2.58] (loopback is ignored)
15:17:50,019 INFO  (main) [i.h.Hyperfoil] Using host name agent-0008-agent-one/10.128.2.58
15:17:50,615 WARN  (main) [o.i.CONFIG] ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
15:17:50,846 WARN  (main) [o.j.s.Configurator] JGRP000014: STABLE.stability_delay has been deprecated: always 0
15:17:50,867 INFO  (main) [i.h.HyperfoilChannelLookup] Connecting to controller 10.128.2.36:7800 (10.128.2.36:7800)
15:17:50,868 INFO  (main) [i.h.HyperfoilChannelLookup] Using 10.128.2.58:7800 as clustering address
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
SLF4J: Ignoring binding found at [jar:file:/deployment/lib/log4j-slf4j-impl-2.19.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See https://www.slf4j.org/codes.html#ignoredBindings for an explanation.
15:17:51,928 INFO  (vert.x-eventloop-thread-0) [i.h.Hyperfoil] Deploying AgentVerticle...
15:17:51,954 INFO  (vert.x-eventloop-thread-0) [i.h.Hyperfoil] AgentVerticle deployed.
15:17:51,968 INFO  (jgroups-5,agent-0008-agent-one-26770) [o.j.threads] JBoss Threads version 3.5.0.Final
15:17:53,039 INFO  (vert.x-eventloop-thread-2) [i.h.c.AgentVerticle] 30168f89-1807-45d3-8f7c-90d95df780c2 Got reply from controller.
15:17:53,096 INFO  (vert.x-eventloop-thread-2) [i.h.c.AgentVerticle] Initializing agent
15:17:53,120 INFO  (vert.x-eventloop-thread-2) [i.h.h.c.HttpClientPoolImpl] Allocating 5 connections (max 5, buffer 0) in 1 executors to http://productpage-bookinfo.apps.a314lp45ocp.lnxne.boe:80
15:18:43,245 WARN  (cpu-watchdog) [i.h.c.u.CpuWatchdog] 15:18:43.244 | CPU 2 was used for 80% which is more than the threshold of 80%
```

**Comment by titlisgupta** [comment]
I have tested in a new cluster which has more resources. The maximum I have tested with is 6.5 core, bechmark is still failing. Now I am not getting any resource or gc error in log, just it seems stuck.

```
name: k8s-hello-world
agents:
  agent-one:
    image: quay.io/ibm-z-performance/hyperfoil:latest
    pod-cpu: "6500m"
    pod-memory: "6Gi"
http:
  host: http://productpage-bookinfo.apps.kiali-qez-413.maistra.upshift.redhat.com
  sharedConnections: 2
duration: 5s
usersPerSec: 2
scenario:
- test:
  - httpRequest:
      GET: /
```

Error: 

<img width="1506" alt="image" src="https://github.com/Hyperfoil/Hyperfoil/assets/8019314/6d6e1336-e8b2-443c-9b9c-ef73c411b47a">

Agent Log:

```
[root@bosz15_l21 bookinfo]# oc logs --v=8 pod/agent-0004-agent-one 
I1031 07:04:45.177165 2386387 loader.go:373] Config loaded from file:  /opt/clusters-deploy/kiali-qez-413/auth/kubeconfig
I1031 07:04:45.183828 2386387 round_trippers.go:463] GET https://api.kiali-qez-413.maistra.upshift.redhat.com:6443/api/v1/namespaces/hyperfoil/pods/agent-0004-agent-one
I1031 07:04:45.183841 2386387 round_trippers.go:469] Request Headers:
I1031 07:04:45.183859 2386387 round_trippers.go:473]     Accept: application/json, */*
I1031 07:04:45.183871 2386387 round_trippers.go:473]     User-Agent: oc/4.13.0 (linux/s390x) kubernetes/8b4d4ed
I1031 07:04:45.198365 2386387 round_trippers.go:574] Response Status: 200 OK in 14 milliseconds
I1031 07:04:45.198380 2386387 round_trippers.go:577] Response Headers:
I1031 07:04:45.198393 2386387 round_trippers.go:580]     Content-Type: application/json
I1031 07:04:45.198404 2386387 round_trippers.go:580]     Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
I1031 07:04:45.198417 2386387 round_trippers.go:580]     X-Kubernetes-Pf-Flowschema-Uid: 04d9916d-16db-4ad6-a131-cbf6e60c69bf
I1031 07:04:45.198427 2386387 round_trippers.go:580]     X-Kubernetes-Pf-Prioritylevel-Uid: ebe6c6db-af38-49a1-8909-95e9824f9c38
I1031 07:04:45.198437 2386387 round_trippers.go:580]     Date: Tue, 31 Oct 2023 11:04:45 GMT
I1031 07:04:45.198450 2386387 round_trippers.go:580]     Audit-Id: 1b185b7e-fa52-44ab-be2f-8a7df6a29f28
I1031 07:04:45.198459 2386387 round_trippers.go:580]     Cache-Control: no-cache, private
I1031 07:04:45.198512 2386387 request.go:1171] Response Body: {"kind":"Pod","apiVersion":"v1","metadata":{"name":"agent-0004-agent-one","namespace":"hyperfoil","uid":"0d09b34e-10fe-4aec-b7e1-d84e6cd68026","resourceVersion":"4522489","creationTimestamp":"2023-10-31T10:28:25Z","labels":{"role":"agent"},"annotations":{"k8s.v1.cni.cncf.io/network-status":"[{\n    \"name\": \"openshift-sdn\",\n    \"interface\": \"eth0\",\n    \"ips\": [\n        \"10.121.3.95\"\n    ],\n    \"default\": true,\n    \"dns\": {}\n}]","openshift.io/scc":"restricted-v2","seccomp.security.alpha.kubernetes.io/pod":"runtime/default"},"managedFields":[{"manager":"okhttp","operation":"Update","apiVersion":"v1","time":"2023-10-31T10:28:25Z","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:labels":{".":{},"f:role":{}}},"f:spec":{"f:containers":{"k:{\"name\":\"hyperfoil-agent\"}":{".":{},"f:command":{},"f:image":{},"f:imagePullPolicy":{},"f:name":{},"f:ports":{".":{},"k:{\"containerPort\":7800,\"protocol\":\"TCP\"}":{".":{},"f:containerPort":{},"f:name":{},"f:protocol":{}}},"f:resources":{".":{},"f: [truncated 4421 chars]
I1031 07:04:45.199152 2386387 round_trippers.go:463] GET https://api.kiali-qez-413.maistra.upshift.redhat.com:6443/api/v1/namespaces/hyperfoil/pods/agent-0004-agent-one/log?container=hyperfoil-agent
I1031 07:04:45.199160 2386387 round_trippers.go:469] Request Headers:
I1031 07:04:45.199171 2386387 round_trippers.go:473]     Accept: application/json, */*
I1031 07:04:45.199182 2386387 round_trippers.go:473]     User-Agent: oc/4.13.0 (linux/s390x) kubernetes/8b4d4ed
I1031 07:04:45.209081 2386387 round_trippers.go:574] Response Status: 200 OK in 9 milliseconds
I1031 07:04:45.209096 2386387 round_trippers.go:577] Response Headers:
I1031 07:04:45.209107 2386387 round_trippers.go:580]     Content-Type: text/plain
I1031 07:04:45.209118 2386387 round_trippers.go:580]     Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
I1031 07:04:45.209128 2386387 round_trippers.go:580]     Date: Tue, 31 Oct 2023 11:04:45 GMT
I1031 07:04:45.209140 2386387 round_trippers.go:580]     Audit-Id: 87f23045-c084-4fa8-ac92-fec447b7e128
I1031 07:04:45.209153 2386387 round_trippers.go:580]     Cache-Control: no-cache, private
10:28:29,511 INFO  (main) [i.h.Hyperfoil] Java: Red Hat, Inc. OpenJDK 64-Bit Server VM 11.0.21 11.0.21+9-LTS (/usr/lib/jvm/java-11-openjdk-11.0.21.0.9-2.el8.s390x), CWD /home/jboss
10:28:29,513 INFO  (main) [i.h.Hyperfoil] Hyperfoil: 0.26-SNAPSHOT (91021e2d8fc4d6671a0ceb4629661f25751fd1ba)
10:28:29,513 INFO  (main) [i.h.Hyperfoil]            DISTRIBUTION:  /deployment
10:28:29,515 INFO  (main) [i.h.Hyperfoil]            ROOT_DIR:      /tmp/hyperfoil
10:28:29,515 INFO  (main) [i.h.Hyperfoil]            BENCHMARK_DIR: /tmp/hyperfoil/benchmark
10:28:29,515 INFO  (main) [i.h.Hyperfoil]            RUN_DIR:       /tmp/hyperfoil/run
10:28:29,515 INFO  (main) [i.h.Hyperfoil]            HOOKS_DIR:     /tmp/hyperfoil/hooks
10:28:29,515 INFO  (main) [i.h.Hyperfoil] Starting Vert.x...
10:28:29,527 INFO  (main) [i.h.Hyperfoil] Agent must choose NIC with best subnet match to controller (10-121-3-90.hyperfoil.hyperfoil.svc.cluster.local/10.121.3.90), available IPs: [/10.121.3.95] (loopback is ignored)
10:28:29,527 INFO  (main) [i.h.Hyperfoil] Using host name agent-0004-agent-one/10.121.3.95
10:28:29,869 WARN  (main) [o.i.CONFIG] ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
10:28:30,043 WARN  (main) [o.j.s.Configurator] JGRP000014: STABLE.stability_delay has been deprecated: always 0
10:28:30,056 INFO  (main) [i.h.HyperfoilChannelLookup] Connecting to controller 10.121.3.90:7800 (10.121.3.90:7800)
10:28:30,057 INFO  (main) [i.h.HyperfoilChannelLookup] Using 10.121.3.95:7800 as clustering address
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
SLF4J: Ignoring binding found at [jar:file:/deployment/lib/log4j-slf4j-impl-2.19.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See https://www.slf4j.org/codes.html#ignoredBindings for an explanation.
10:28:30,948 INFO  (vert.x-eventloop-thread-0) [i.h.Hyperfoil] Deploying AgentVerticle...
10:28:30,962 INFO  (vert.x-eventloop-thread-0) [i.h.Hyperfoil] AgentVerticle deployed.
10:28:30,974 INFO  (jgroups-10,agent-0004-agent-one-37389) [o.j.threads] JBoss Threads version 3.5.0.Final
10:28:32,026 INFO  (vert.x-eventloop-thread-2) [i.h.c.AgentVerticle] 921f9ba2-9a95-42e6-a051-a97c023b9ef4 Got reply from controller.
10:28:32,086 INFO  (vert.x-eventloop-thread-2) [i.h.c.AgentVerticle] Initializing agent
10:28:32,104 INFO  (vert.x-eventloop-thread-2) [i.h.h.c.HttpClientPoolImpl] Allocating 2 connections (max 2, buffer 0) in 1 executors to http://productpage-bookinfo.apps.kiali-qez-413.maistra.upshift.redhat.com:80
```

**Comment by titlisgupta** [comment]
Found some more logs in hyperfoil-controller. Seems like the agent is failing to start at first but then getting completed later. 

```
12:18:29,554 INFO  (vert.x-worker-thread-10) [i.h.c.u.PersistenceUtil] Stored benchmark 'k8s-hello-world' in /var/hyperfoil/benchmark/k8s-hello-world.yaml
12:19:15,310 INFO  (vert.x-eventloop-thread-2) [i.h.c.u.PersistenceUtil] Stored benchmark 'k8s-hello-world' in /var/hyperfoil/run/0008/k8s-hello-world.yaml
12:19:15,311 INFO  (vert.x-eventloop-thread-2) [i.h.c.ControllerVerticle] Starting agents for run 0008
12:19:16,062 ERROR (vert.x-eventloop-thread-2) [i.h.c.ControllerVerticle] Failed to start agent agent-one java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/exc/StreamConstraintsException
	at com.fasterxml.jackson.databind.node.JsonNodeFactory.textNode(JsonNodeFactory.java:309)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer._deserializeAnyScalar(JsonNodeDeserializer.java:667)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:109)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:25)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4801)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:3084)
	at io.fabric8.kubernetes.api.model.Quantity$Deserializer.deserialize(Quantity.java:248)
	at io.fabric8.kubernetes.api.model.Quantity$Deserializer.deserialize(Quantity.java:243)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:623)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:449)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:32)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:359)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4825)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3817)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:241)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:195)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:474)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:430)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:251)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:802)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:322)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:318)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.lambda$createNew$0(BaseOperation.java:333)
	at io.fabric8.kubernetes.api.model.DoneablePod.done(DoneablePod.java:26)
	at io.hyperfoil.deploy.k8s.K8sDeployer.start(K8sDeployer.java:299)
	at io.hyperfoil.clustering.ControllerVerticle.lambda$startBenchmark$26(ControllerVerticle.java:567)
	at io.vertx.core.impl.ContextBase.lambda$null$0(ContextBase.java:137)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
	at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:135)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.core.exc.StreamConstraintsException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
	... 49 more

12:19:24,210 INFO  (vert.x-eventloop-thread-2) [i.h.c.ControllerVerticle] Starting benchmark k8s-hello-world - run 0008
12:19:24,396 INFO  (vert.x-eventloop-thread-2) [i.h.c.ControllerPhase] 0008 main changing status NOT_STARTED to STARTING
12:19:24,401 INFO  (vert.x-eventloop-thread-2) [i.h.c.ControllerPhase] 0008 main changing status STARTING to RUNNING
12:19:28,396 INFO  (vert.x-eventloop-thread-2) [i.h.c.ControllerPhase] 0008 main changing status RUNNING to FINISHING
12:19:28,401 INFO  (vert.x-eventloop-thread-2) [i.h.c.ControllerPhase] 0008 main changing status FINISHING to FINISHED
12:19:28,411 INFO  (vert.x-eventloop-thread-2) [i.h.c.ControllerPhase] 0008 main changing status FINISHED to TERMINATED
12:19:28,411 INFO  (vert.x-eventloop-thread-2) [i.h.c.ControllerVerticle] 0008 All phases are terminated.
12:19:28,411 WARN  (vert.x-eventloop-thread-2) [i.h.c.ControllerVerticle] Run 0008 already completed.
12:19:28,412 INFO  (vert.x-eventloop-thread-2) [i.h.c.ControllerVerticle] Run 0008: completing stats for phase main
```

**Comment by franz1981** [comment]
how this end up @barreiro @titlisgupta ?
I see others having this same issue

**Comment by franz1981** [comment]
A similar one seems https://github.com/apache/iceberg/issues/9355 although I cannot see its resolution and the jackson dependency seems in

**Comment by ankitasgupta** [comment]
@franz1981 we had to use an older version of Hyperfoil. Used tag hyperfoil-all-0.25 and put my changes #318 there

**Comment by franz1981** [comment]
Many thanks @ankitasgupta 
So, it means that using the latest released one with your changes didn't worked?

**Comment by ankitasgupta** [comment]
@franz1981 yes, it didn't work. Being able to increase the cpu is needed in later stage but for simple load not much cpu is needed, actually I was able to make it work with even 2 core. The real issue I guess was the latest changes.

**Comment by franz1981** [comment]
Perfect, many thanks, so, in short:
1. https://github.com/Hyperfoil/Hyperfoil/commits/hyperfoil-all-0.25.1/ is likely breaking the Jackson dependencies causing the `ClassNotFoundException` to happen - but I have to verify it
2. 104770799f15ce93488f0424fa8fa6da10a8ec81 from @barreiro  maybe fixed it - need to verify it
3. #318 is required to allow cpu settings to work and save other later problems

Which means that if we can verify that current version just work, we need to release it to unblock other users.
Currently the easier option is to use 0.25

**Comment by franz1981** [comment]
I've verified that 2. was the case here, so thanks @barreiro that has fixed this issue, see the distribution of jackson here:
![image](https://github.com/Hyperfoil/Hyperfoil/assets/13125299/693fa48e-919f-4b91-82d6-218076bbde08)

which doesn't contain the mentioned exception. 
I'm still not very happy because it doesn't tell why the exception was loaded, but that's a separate problem.
