### ISSUE TITLE
Sequences not executing

### ISSUE THREAD

**Issue by edeandrea** [Hyperfoil/Hyperfoil#317]
I have a benchmark where I need to execute a request to get a payload body, then POST it back to a different URI. The `doFight` sequence in the below benchmark never seems to be executed.

Here's how to run this benchmark:
1. Clone https://github.com/quarkusio/quarkus-super-heroes
2. `cd` into the `quarkus-super-heroes/rest-fights` directory
3. Run `docker compose -f deploy/docker-compose/java17.yml up`
4. Run Hyperfoil (I'm running the Hyperfoil CLI via `docker run --name hyperfoil_cli -it --rm -v $(pwd):/benchmarks:z -u $(id -u):$(id -g) --platform linux/amd64 --network=host quay.io/hyperfoil/hyperfoil cli`)
5. Upload and execute the benchmark below

Not sure if this matters, but I'm running on a Mac M1, MacOS Sonoma 14.1.

```yaml
# This Hyperfoil benchmark performs a "Perform fight" operation, which runs a sequence of requests in each iteration:
# 1) Perform a GET to /api/fights/randomfighters to retrieve random fighters, storing the result in a variable
# 2) Pause to look at the fighters (as a human user might)
# 3) Perform a POST to /api/fights to perform the fight, sending the result from step 1 as the request body

# Here is a list of all the parameters and their default values that can be adjusted when running:
#
# FIGHT_PROTOCOL=http (The protocol used by the benchmark)
# FIGHT_HOST=localhost (The host the rest-fights application is running on)
# FIGHT_PORT=8082 (The port the rest-fights application is running on)
# SHARED_CONNECTIONS=400 (The number of connections to share across the requests)
# USERS_PER_SEC=20 (The number of users per second)
# MAX_SESSIONS=200 (The maximum number of hyperfoil sessions to make available)
# DURATION=3m (The duration to run the benchmark)
# PAUSE_TIME_DURATION=3s (The duration to pause, as described in step 2 of the workflow)

name: perform-fight
http:
  - protocol: !param FIGHT_PROTOCOL http
    host: !param FIGHT_HOST localhost
    port: !param FIGHT_PORT 8082
    name: fights-host
    sharedConnections: !param SHARED_CONNECTIONS 400

phases:
  - performFight:
      constantRate:
        usersPerSec: !param USERS_PER_SEC 20
        maxSessions: !param MAX_SESSIONS 200
        duration: !param DURATION 10s
        scenario:
          # This is written using initialSequences because of https://github.com/Hyperfoil/Hyperfoil/issues/311
          # Although something still seems to be wrong because the phase never terminates upon execution.
          initialSequences:
            - getRandomFighters:
                - httpRequest:
                    GET: /api/fights/randomfighters
                    headers:
                      accept: application/json
                    handler:
                      body:
                        - json:
                            query: .
                            format: BYTES
                            toVar: randomFighters

          sequences:
            - doFight:
                - httpRequest:
                    POST: /api/fights
                    headers:
                      content-type: application/json
                      accept: application/json
                    body:
                      fromVar: randomFighters


```

**Comment by edeandrea** [comment]
Upon some further investigation, it seems that the `randomFighters` variable is not being set for some reason.

If I add this:

```yaml
# This Hyperfoil benchmark performs a "Perform fight" operation, which runs a sequence of requests in each iteration:
# 1) Perform a GET to /api/fights/randomfighters to retrieve random fighters, storing the result in a variable
# 2) Pause to look at the fighters (as a human user might)
# 3) Perform a POST to /api/fights to perform the fight, sending the result from step 1 as the request body

# Here is a list of all the parameters and their default values that can be adjusted when running:
#
# FIGHT_PROTOCOL=http (The protocol used by the benchmark)
# FIGHT_HOST=localhost (The host the rest-fights application is running on)
# FIGHT_PORT=8082 (The port the rest-fights application is running on)
# SHARED_CONNECTIONS=400 (The number of connections to share across the requests)
# USERS_PER_SEC=20 (The number of users per second)
# MAX_SESSIONS=200 (The maximum number of hyperfoil sessions to make available)
# DURATION=3m (The duration to run the benchmark)
# PAUSE_TIME_DURATION=3s (The duration to pause, as described in step 2 of the workflow)

name: perform-fight
http:
  - protocol: !param FIGHT_PROTOCOL http
    host: !param FIGHT_HOST localhost
    port: !param FIGHT_PORT 8082
    name: fights-host
    sharedConnections: !param SHARED_CONNECTIONS 400

phases:
  - performFight:
      constantRate:
        usersPerSec: !param USERS_PER_SEC 20
        maxSessions: !param MAX_SESSIONS 200
        duration: !param DURATION 10s
        scenario:
          # This is written using initialSequences because of https://github.com/Hyperfoil/Hyperfoil/issues/311
          # Although something still seems to be wrong because the phase never terminates upon execution.
          initialSequences:
            - getRandomFighters:
                - httpRequest:
                    GET: /api/fights/randomfighters
                    headers:
                      accept: application/json
                    handler:
                      onCompletion:
                        - log: Completed with ${randomFighters}
                      body:
                        - json:
                            query: .
                            format: STRING
                            toVar: randomFighters
                - log: randomFighters = ${randomFighters}
                - newSequence: doFight

          sequences:
            - doFight:
                - httpRequest:
                    POST: /api/fights
                    headers:
                      content-type: application/json
                      accept: application/json
                    body: 
                      fromVar: randomFighters
```

when I look at the logs I see lots of

```
6:34:37,106 INFO  (vert.x-eventloop-thread-0) [i.h.c.ControllerPhase] 0017 performFight changing status FINISHING to FINISHED
16:34:37,222 INFO  (epollEventLoopGroup-25-1) [i.h.c.s.LogAction] randomFighters = <not set>
16:34:37,271 INFO  (epollEventLoopGroup-25-1) [i.h.c.s.LogAction] randomFighters = <not set>
16:34:37,283 INFO  (epollEventLoopGroup-25-1) [i.h.c.s.LogAction] randomFighters = <not set>
16:34:37,320 INFO  (epollEventLoopGroup-25-1) [i.h.c.s.LogAction] randomFighters = <not set>
16:34:37,320 INFO  (epollEventLoopGroup-25-1) [i.h.c.s.LogAction] randomFighters = <not set>
16:34:37,439 INFO  (epollEventLoopGroup-25-1) [i.h.c.s.LogAction] randomFighters = <not set>
16:34:37,518 INFO  (epollEventLoopGroup-25-1) [i.h.c.s.LogAction] randomFighters = <not set>
16:34:37,519 INFO  (epollEventLoopGroup-25-1) [i.h.c.s.LogAction] randomFighters = <not set>
16:34:37,590 INFO  (epollEventLoopGroup-25-1) [i.h.c.s.LogAction] randomFighters = <not set>
16:34:37,626 INFO  (epollEventLoopGroup-25-1) [i.h.c.s.LogAction] randomFighters = <not set>
16:34:37,628 INFO  (epollEventLoopGroup-25-1) [i.h.c.s.LogAction] randomFighters = <not set>
16:34:37,628 INFO  (epollEventLoopGroup-25-1) [i.h.c.s.LogAction] randomFighters = <not set>
16:34:37,676 INFO  (epollEventLoopGroup-25-1) [i.h.c.s.LogAction] randomFighters = <not set>
16:34:37,922 INFO  (epollEventLoopGroup-25-1) [i.h.c.s.LogAction] randomFighters = <not set>
16:34:37,940 INFO  (vert.x-eventloop-thread-0) [i.h.c.ControllerPhase] 0017 performFight changing status FINISHED to TERMINATED
```

**Comment by franz1981** [comment]
I'll need to check if replacing the json body's handler with a plain

```yaml
            handler:
              body:
                store:
                  toVar: randomFighters
```
while keeping the rest as it is could work.

**Comment by edeandrea** [comment]
This did not work. It required me to specify `query`

**Comment by franz1981** [comment]
update: using straight the text approach worked (but still using `awaitAllResponses`.

What's not working, instead, is to extract a variable which can be used to split the response body into to json queries, to extract the `.hero` and `.villain` part of it.
Investigating now on this other one.

**Comment by franz1981** [comment]
I've updated the unit tests for #311

**Comment by franz1981** [comment]
@edeandrea I've solved the issue by following the error message (and debugging to understand what it really means..) and

```yaml
                - httpRequest:
                    GET: /api/fights/randomfighters
                    headers:
                      accept: application/json
                    handler:
                      body:
                        store:
                          toVar: randomFighters
                          format: BYTES
                - json:
                    fromVar: randomFighters
                    format: STRING
                    query: .hero
                    toVar: randomHero
                - json:
                    fromVar: randomFighters
                    format: STRING
                    query: .villain
                    toVar: randomVillain

```
this is working for me, indeed the error was 

```java
java.lang.IllegalStateException: Unexpected format of input (expecting byte[]): {"hero":{"name":"Fallback hero","level":1,"picture":"https://dummyimage.com/280x380/1e8fff/ffffff&text=Fallback+Hero","powers":"Fallback hero powers"},"villain":{"name":"Fallback villain","level":45,"picture":"https://dummyimage.com/280x380/b22222/ffffff&text=Fallback+Villain","powers":"Fallback villain powers"}}
        at io.hyperfoil.core.steps.JsonStep.invoke(JsonStep.java:45)
        at io.hyperfoil.api.session.SequenceInstance.progress(SequenceInstance.java:33)
        at io.hyperfoil.core.session.SessionImpl.runSession(SessionImpl.java:279)
        at io.hyperfoil.core.session.SessionImpl.run(SessionImpl.java:233)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

Meaning that the `json` formatting *requires a mandatory* BYTES format IN, to work, and `body`'s `store` cannot do anything about it, but just providing the right type.

**Comment by edeandrea** [comment]
I've been able to get it to work...

https://github.com/quarkusio/quarkus-super-heroes/blob/main/rest-fights/hyperfoil/perform-fight.hf.yml
