### ISSUE TITLE
Benchmark completes with java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Hyperfoil#32]
With the simple benchmark below;

```
name: single-request
http:
  baseUrl: http://localhost:8080
phases:
- example:
    constantPerSec: 
      usersPerSec: 10
      duration: 60s
      scenario:
      - test:
        - httpRequest:
            GET: /fruits
            sync: true
```

The benchmark completes, but outputs the following exceptions.  Just before the first 1s stat interval;

```
11:47:39,749 ERROR (nioEventLoopGroup-9-1) [i.h.a.s.SequenceInstance] #6 test(0) failure invoking step io.hyperfoil.core.steps.HttpRequestStep@31f7f610 java.lang.IndexOutOfBoundsException: index 16
	at java.util.concurrent.atomic.AtomicReferenceArray.checkedByteOffset(AtomicReferenceArray.java:78)
	at java.util.concurrent.atomic.AtomicReferenceArray.get(AtomicReferenceArray.java:125)
	at io.hyperfoil.api.statistics.Statistics.active(Statistics.java:247)
	at io.hyperfoil.api.statistics.Statistics.incrementRequests(Statistics.java:74)
	at io.hyperfoil.core.steps.HttpRequestStep.invoke(HttpRequestStep.java:156)
	at io.hyperfoil.api.session.SequenceInstance.progress(SequenceInstance.java:27)
	at io.hyperfoil.core.session.SessionImpl.runSession(SessionImpl.java:244)
	at io.hyperfoil.core.session.SessionImpl.call(SessionImpl.java:195)
	at io.hyperfoil.core.session.SessionImpl.call(SessionImpl.java:26)
	at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:73)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

And at the end of the run;

```
11:47:39,821 WARN  (nioEventLoopGroup-9-1) [i.h.c.s.SessionImpl] #6 Session completed with requests in-flight!
java.lang.RuntimeException: java.lang.IndexOutOfBoundsException: index 16
11:47:39,823 ERROR (nioEventLoopGroup-9-1) [i.h.c.s.SessionImpl] #6 Uncaught error java.lang.IndexOutOfBoundsException: index 16
	at java.util.concurrent.atomic.AtomicReferenceArray.checkedByteOffset(AtomicReferenceArray.java:78)
	at java.util.concurrent.atomic.AtomicReferenceArray.get(AtomicReferenceArray.java:125)
	at io.hyperfoil.api.statistics.Statistics.active(Statistics.java:247)
	at io.hyperfoil.api.statistics.Statistics.incrementResets(Statistics.java:94)
	at io.hyperfoil.core.steps.HttpResponseHandlersImpl.handleThrowable(HttpResponseHandlersImpl.java:121)
	at io.hyperfoil.core.steps.HttpResponseHandlersImpl.handleThrowable(HttpResponseHandlersImpl.java:28)
	at io.hyperfoil.core.client.netty.Http1xConnection.cancelRequests(Http1xConnection.java:137)
	at io.hyperfoil.core.client.netty.Http1xConnection.close(Http1xConnection.java:209)
	at io.hyperfoil.core.session.SessionImpl.cancelRequests(SessionImpl.java:289)
	at io.hyperfoil.core.session.SessionImpl.runSession(SessionImpl.java:273)
	at io.hyperfoil.core.session.SessionImpl.call(SessionImpl.java:195)
	at io.hyperfoil.core.session.SessionImpl.call(SessionImpl.java:26)
	at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:73)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by johnaohara** [comment]
For clarity, this occurs when executing benchmark with `run-local` command

**Comment by rvansa** [comment]
Fixed.
