### ISSUE TITLE
[minor] getting error when running `report` command (but the report works)

### ISSUE THREAD

**Issue by helio-frota** [Hyperfoil/Hyperfoil#339]
Hi, the report works :+1: 

![2024-04-30_09-57](https://github.com/Hyperfoil/Hyperfoil/assets/6443576/f8ea3166-f81c-434e-b76c-da64ccbbb5e8)

But the command shows this error:

I'm using the latest release hyperfoil-0.25.2

```console
[hyperfoil@in-vm]$ report --destination=/home/heliofrota/
Written to /home/heliofrota/0002.html
Exception in thread "Thread-8" java.lang.UnsatisfiedLinkError: Can't load library: /usr/lib/jvm/java-17-openjdk-17.0.9.0.9-3.fc39.x86_64/lib/libawt_xawt.so
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2398)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1953)
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
	at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:315)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:285)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2403)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
	at java.base/java.lang.System.loadLibrary(System.java:1989)
	at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:1392)
	at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:1390)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at java.desktop/java.awt.Toolkit.loadLibraries(Toolkit.java:1389)
	at java.desktop/java.awt.Toolkit.initStatic(Toolkit.java:1427)
	at java.desktop/java.awt.Toolkit.<clinit>(Toolkit.java:1401)
	at java.desktop/java.awt.Desktop.isDesktopSupported(Desktop.java:329)
	at io.hyperfoil.cli.commands.ServerCommand.openInBrowser(ServerCommand.java:60)
	at io.hyperfoil.cli.commands.Report.execute(Report.java:64)
	at io.hyperfoil.cli.commands.Report.execute(Report.java:16)
	at org.aesh.command.impl.operator.EndOperator.execute(EndOperator.java:41)
	at org.aesh.command.impl.Executions$ExecutionImpl.execute(Executions.java:222)
File /home/heliofrota/0002.html already exists, overwrite? [y/N]: 	at org.aesh.readline.Process.run(Process.java:80)
```

**Comment by helio-frota** [comment]
this is a minor... I'm using only the headless

```
➜  ~ dnf list installed | rg jdk
copy-jdk-configs.noarch                              4.1-3.fc39                          @anaconda                  
java-17-openjdk-headless.x86_64                      1:17.0.9.0.9-3.fc39                 @updates            
```

after installing openjdk (full) the error is gone

```
[hyperfoil@in-vm]$ Opening in existing browser session.
```

:+1:

**Comment by johnaohara** [comment]
@helio-frota thanks for the update. I think we should add this information to the FAQ's
