### ISSUE TITLE
`TwoServersTest` started failing after #410

### ISSUE THREAD

**Issue by lampajr** [Hyperfoil/Hyperfoil#439]
**Describe the bug**
After merging https://github.com/Hyperfoil/Hyperfoil/pull/410, master checks started failing at:
```bash
[INFO] Running io.hyperfoil.http.TwoServersTest
Error:  Tests run: 5, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 3.959 s <<< FAILURE! -- in io.hyperfoil.http.TwoServersTest
Error:  io.hyperfoil.http.TwoServersTest.testTwoServers -- Time elapsed: 3.754 s <<< ERROR!
java.util.ConcurrentModificationException
	at java.base/java.util.ArrayDeque.forEach(ArrayDeque.java:890)
	at io.hyperfoil.impl.CollectingVisitor.visit(CollectingVisitor.java:35)
	at io.hyperfoil.impl.ReflectionAcceptor.accept(ReflectionAcceptor.java:33)
	at io.hyperfoil.impl.CollectingVisitor.visit(CollectingVisitor.java:46)
	at io.hyperfoil.impl.ReflectionAcceptor.accept(ReflectionAcceptor.java:33)
	at io.hyperfoil.impl.CollectingVisitor.visit(CollectingVisitor.java:46)
	at io.hyperfoil.impl.CollectingVisitor.lambda$visit$0(CollectingVisitor.java:35)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092)
	at io.hyperfoil.impl.CollectingVisitor.visit(CollectingVisitor.java:35)
	at io.hyperfoil.impl.ReflectionAcceptor.accept(ReflectionAcceptor.java:33)
	at io.hyperfoil.impl.CollectingVisitor.visit(CollectingVisitor.java:46)
	at io.hyperfoil.impl.CollectingVisitor.lambda$visit$0(CollectingVisitor.java:35)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092)
	at io.hyperfoil.impl.CollectingVisitor.visit(CollectingVisitor.java:35)
	at io.hyperfoil.impl.ReflectionAcceptor.accept(ReflectionAcceptor.java:33)
	at io.hyperfoil.impl.CollectingVisitor.visit(CollectingVisitor.java:46)
	at io.hyperfoil.impl.ReflectionAcceptor.accept(ReflectionAcceptor.java:33)
	at io.hyperfoil.impl.CollectingVisitor.visit(CollectingVisitor.java:46)
	at io.hyperfoil.impl.ReflectionAcceptor.accept(ReflectionAcceptor.java:33)
	at io.hyperfoil.impl.CollectingVisitor.visit(CollectingVisitor.java:46)
	at io.hyperfoil.impl.ReflectionAcceptor.accept(ReflectionAcceptor.java:33)
	at io.hyperfoil.impl.CollectingVisitor.visit(CollectingVisitor.java:46)
	at io.hyperfoil.impl.ReflectionAcceptor.accept(ReflectionAcceptor.java:33)
	at io.hyperfoil.impl.CollectingVisitor.visit(CollectingVisitor.java:46)
	at io.hyperfoil.impl.ReflectionAcceptor.accept(ReflectionAcceptor.java:33)
	at io.hyperfoil.impl.CollectingVisitor.visit(CollectingVisitor.java:46)
	at io.hyperfoil.impl.CollectingVisitor.lambda$visit$1(CollectingVisitor.java:37)
	at java.base/java.util.IdentityHashMap.forEach(IdentityHashMap.java:1[354](https://github.com/Hyperfoil/Hyperfoil/actions/runs/10633876164/job/29480175064#step:9:355))
	at io.hyperfoil.impl.CollectingVisitor.visit(CollectingVisitor.java:37)
	at io.hyperfoil.impl.ReflectionAcceptor.accept(ReflectionAcceptor.java:33)
	at io.hyperfoil.impl.CollectingVisitor.visit(CollectingVisitor.java:46)
	at io.hyperfoil.impl.ReflectionAcceptor.accept(ReflectionAcceptor.java:33)
	at io.hyperfoil.impl.CollectingVisitor.visit(CollectingVisitor.java:46)
	at io.hyperfoil.impl.ReflectionAcceptor.accept(ReflectionAcceptor.java:33)
	at io.hyperfoil.impl.CollectingVisitor.visit(CollectingVisitor.java:46)
	at io.hyperfoil.impl.ReflectionAcceptor.accept(ReflectionAcceptor.java:33)
	at io.hyperfoil.impl.CollectingVisitor.visit(CollectingVisitor.java:46)
	at io.hyperfoil.impl.ReflectionAcceptor.accept(ReflectionAcceptor.java:33)
	at io.hyperfoil.impl.CollectingVisitor.visit(CollectingVisitor.java:46)
	at io.hyperfoil.impl.ReflectionAcceptor.accept(ReflectionAcceptor.java:33)
	at io.hyperfoil.impl.CollectingVisitor.visit(CollectingVisitor.java:46)
	at io.hyperfoil.impl.ReflectionAcceptor.accept(ReflectionAcceptor.java:33)
	at io.hyperfoil.impl.CollectingVisitor.visit(CollectingVisitor.java:46)
	at io.hyperfoil.impl.CollectingVisitor.visit(CollectingVisitor.java:43)
	at io.hyperfoil.impl.ReflectionAcceptor.accept(ReflectionAcceptor.java:33)
	at io.hyperfoil.impl.CollectingVisitor.visit(CollectingVisitor.java:46)
	at io.hyperfoil.impl.ReflectionAcceptor.accept(ReflectionAcceptor.java:33)
	at io.hyperfoil.impl.CollectingVisitor.visit(CollectingVisitor.java:46)
	at io.hyperfoil.impl.CollectingVisitor.visit(CollectingVisitor.java:43)
	at io.hyperfoil.impl.ReflectionAcceptor.accept(ReflectionAcceptor.java:33)
	at io.hyperfoil.impl.CollectingVisitor.visit(CollectingVisitor.java:46)
	at io.hyperfoil.impl.CollectingVisitor.visit(CollectingVisitor.java:43)
	at io.hyperfoil.impl.CollectingVisitor.visit(CollectingVisitor.java:21)
	at io.hyperfoil.api.config.Scenario.<init>(Scenario.java:54)
	at io.hyperfoil.api.config.ScenarioBuilder.build(ScenarioBuilder.java:148)
	at io.hyperfoil.api.config.PhaseBuilder.buildPhase(PhaseBuilder.java:195)
	at io.hyperfoil.api.config.PhaseBuilder.lambda$build$4(PhaseBuilder.java:168)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180)
	at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104)
	at java.base/java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:711)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.hyperfoil.api.config.PhaseBuilder.build(PhaseBuilder.java:169)
	at io.hyperfoil.api.config.BenchmarkBuilder.lambda$build$1(BenchmarkBuilder.java:147)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.hyperfoil.api.config.BenchmarkBuilder.build(BenchmarkBuilder.java:147)
	at io.hyperfoil.core.session.BaseScenarioTest.runScenario(BaseScenarioTest.java:25)
	at io.hyperfoil.http.TwoServersTest.testTwoServers(TwoServersTest.java:83)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at io.vertx.junit5.VertxExtension.interceptTestMethod(VertxExtension.java:142)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
``` 

what is weird is that in https://github.com/Hyperfoil/Hyperfoil/pull/410 all checks were working!

**To Reproduce**

See https://github.com/Hyperfoil/Hyperfoil/actions/runs/10633876164/job/29480175064

**Expected behavior**
Tests succeed

**Additional context**
Tests in https://github.com/Hyperfoil/Hyperfoil/pull/410 might have been executed before some deps upgrades that have been merged in the last couple of days.

**Comment by lampajr** [comment]
Another thing, locally it is properly working.

**Comment by lampajr** [comment]
Looks like a flaky test, after a manual restart it worked, see https://github.com/Hyperfoil/Hyperfoil/actions/runs/10633876164/job/29480959282

**Comment by franz1981** [comment]
That's some racy behaviour: java.util.ConcurrentModificationException :/ likely

**Comment by lampajr** [comment]
> That's some racy behaviour: java.util.ConcurrentModificationException :/ likely

+1 I will try to refactor it to (hopefully) avoid such kind of issues
