### ISSUE TITLE
JSON stats persister errors

### ISSUE THREAD

**Issue by rvansa** [Hyperfoil/Hyperfoil#45]
I've seen some errors from the JSON stats persister when the deployment fails:
```
07:46:08,818 ERROR (vert.x-worker-thread-9) [i.h.c.ControllerVerticle] Failed to persist statistics com.fasterxml.jackson.core.JsonGenerationException: Current context not Object but root
        at com.fasterxml.jackson.core.JsonGenerator._reportError(JsonGenerator.java:1961)
        at com.fasterxml.jackson.core.json.UTF8JsonGenerator.writeEndObject(UTF8JsonGenerator.java:351)
        at io.hyperfoil.core.impl.statistics.StatisticsStore.walkPhaseIterFork(StatisticsStore.java:272)
        at io.hyperfoil.core.impl.statistics.StatisticsStore.writeJson(StatisticsStore.java:307)
        at io.hyperfoil.core.impl.statistics.StatisticsStore.persist(StatisticsStore.java:480)
        at io.hyperfoil.clustering.ControllerVerticle.lambda$persistRun$31(ControllerVerticle.java:503)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:272)
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by willr3** [comment]
I guess the PR didn't automatically close this... does it need to be in the commit message and not just the PR message?

**Comment by rvansa** [comment]
I guess it must be in the commit.
