### ISSUE TITLE
BigResponseParsingTest occasionally failing

### ISSUE THREAD

**Issue by lampajr** [Hyperfoil/Hyperfoil#477]
**Describe the bug**

BigResponseParsingTest is occasionally failing in the CI:

```bash
Error:  Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.034 s <<< FAILURE! -- in io.hyperfoil.http.BigResponseParsingTest
Error:  io.hyperfoil.http.BigResponseParsingTest.test(VertxTestContext) -- Time elapsed: 0.029 s <<< FAILURE!
java.lang.AssertionError
	at io.hyperfoil.http.connection.SharedConnectionPool.acquireNow(SharedConnectionPool.java:71)
	at io.hyperfoil.http.connection.SharedConnectionPool.acquire(SharedConnectionPool.java:105)
	at io.hyperfoil.http.BigResponseParsingTest.lambda$test$4(BigResponseParsingTest.java:118)
	at io.vertx.core.impl.future.FutureImpl$4.onSuccess(FutureImpl.java:176)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:66)
	at io.vertx.core.impl.future.FutureImpl.addListener(FutureImpl.java:231)
	at io.vertx.core.impl.future.FutureImpl.onComplete(FutureImpl.java:199)
	at io.hyperfoil.http.BigResponseParsingTest.test(BigResponseParsingTest.java:91)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at io.vertx.junit5.VertxExtension.interceptTestMethod(VertxExtension.java:142)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```

**To Reproduce**

See https://github.com/Hyperfoil/Hyperfoil/actions/runs/11288804204 as example

**Expected behavior**
The test should always work!

**Additional context**
n/a

**Comment by lampajr** [comment]
Looks like it is breaking here https://github.com/Hyperfoil/Hyperfoil/blob/a7b0f9bc7cfe101eb9afa1eae288a8ede81c15e4/http/src/main/java/io/hyperfoil/http/connection/SharedConnectionPool.java#L71

**Comment by franz1981** [comment]
That could be a quirk of the way we run tests (and not only - the way be boostraps our scenarios) - see [https://github.com/Hyperfoil/Hyperfoil/commit/b264d47eb5170339207b4a8281e5fa544b16ed5c#diff-057a59eb095cc23b59be6f9f46ce9163940a3e783981ea99c88f637aba406fe1R98 where you can print which thread start it.
](https://github.com/Hyperfoil/Hyperfoil/commit/b264d47eb5170339207b4a8281e5fa544b16ed5c#diff-cea7a9d463cd7ef85e8872e247dd8303107620bd3394d28c02fccd9b2fdefedeR57) comment

**Comment by lampajr** [comment]
> That could be a quirk of the way we run tests 

+1, I tried locally but I am not able to reproduce the same.. at that breakpoint the code is correctly executed in the event loop. 

Moreover I tried re-running the CI for the third time and it worked, thus I think there are some specific situation that can cause the issue to appear or not - this confirms the tests might not be as stable as we think but at least I can lower a bit the priority of this, at least until we see this happen more often.

**Comment by franz1981** [comment]
Try to force proceed to happen without ever going in the scheduling case, in a test which create the scenario and run it in the test itself

**Comment by lampajr** [comment]
AS you can see here https://github.com/Hyperfoil/Hyperfoil/blob/a7b0f9bc7cfe101eb9afa1eae288a8ede81c15e4/http/src/test/java/io/hyperfoil/http/BigResponseParsingTest.java#L88-L120

the test manually call the `pool.acquire` and that portion of the code should be already running in the event loop

**Comment by lampajr** [comment]
Closing this as stale issue, I did not see this happen in recent times - we can still re-open it if we hit the issue again
