### ISSUE TITLE
BlockedThreadChecker

### ISSUE THREAD

**Issue by willr3** [Hyperfoil/Hyperfoil#70]
I'm trying to upload the benchmark from the cli.sh:

```
╭─ 16:11:20 wreicher laptop ~/code/github/Hyperfoil/Hyperfoil  ⚑ master
╰▷ curl hyperfoil.apps.cloud.scalelab/version
{
  "version" : "0.6-SNAPSHOT",
  "commitId" : "1322f7aba1ea30317dc5565dd2f23c261a9ae592",
  "deploymentId" : "39ae4b04-741b-4454-be25-03ecc800ac30",
  "serverTime" : "2019/12/04 22:17:01.181"
}
╭─ 16:09:18 wreicher laptop ~/code/github/Hyperfoil/Hyperfoil  ⚑ (HEAD detached at 1322f7ab)
╰▷ ./distribution/target/distribution/bin/cli.sh 
[hyperfoil]$ connect hyperfoil.apps.cloud.scalelab -p 80
Connected!
[hyperfoil@hyperfoil]$ upload /home/wreicher/perfWork/scalelab/serverless-scale.hf.yaml
Loaded benchmark serverless-scale, uploading...
ERROR: Request did not complete within 30 seconds.
Failed to upload the benchmark.
[hyperfoil@hyperfoil]$ exit
```

on the server:
```
oc log -n hyperfoil pod/hyperfoil-controller
18:34:31,878 WARN  (vertx-blocked-thread-checker) [i.v.c.i.BlockedThreadChecker] Thread Thread[vert.x-worker-thread-16,5,main]=Thread[vert.x-worker-thread-16,5,main] has been blocked for 9804429 ms, time limit is 60000 ms io.vertx.core.VertxException: Thread blocked
	at java.lang.Object.wait(Native Method)
	at java.io.PipedInputStream.read(PipedInputStream.java:326)
	at java.io.PipedInputStream.read(PipedInputStream.java:377)
	at java.io.InputStream.read(InputStream.java:101)
	at java.nio.file.Files.copy(Files.java:2908)
	at java.nio.file.Files.copy(Files.java:3027)
	at io.hyperfoil.deploy.k8s.K8sDeployer.downloadAgentLog(K8sDeployer.java:192)
	at io.hyperfoil.clustering.ControllerVerticle.lambda$downloadAgentLog$40(ControllerVerticle.java:770)
	at io.hyperfoil.clustering.ControllerVerticle$$Lambda$683/844177198.handle(Unknown Source)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
	at io.vertx.core.impl.ContextImpl$$Lambda$273/1986676021.run(Unknown Source)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at io.vertx.core.impl.TaskQueue$$Lambda$270/2059282367.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by rvansa** [comment]
I believe this was fixed in edf3f82d
