### ISSUE TITLE
Phase got stuck with IllegalStateException

### ISSUE THREAD

**Issue by rvansa** [Hyperfoil/Hyperfoil#78]
```
17:14:15,701 ERROR (nioEventLoopGroup-2-5) [i.h.c.i.PhaseInstanceImpl] Error during session acquisition java.lang.IllegalStateException: Queue full
        at java.util.AbstractQueue.add(AbstractQueue.java:98)
        at java.util.concurrent.ArrayBlockingQueue.add(ArrayBlockingQueue.java:312)
        at java.util.concurrent.LinkedBlockingQueue.drainTo(LinkedBlockingQueue.java:743)
        at io.hyperfoil.core.impl.ElasticPoolImpl.acquire(ElasticPoolImpl.java:39)
        at io.hyperfoil.core.impl.PhaseInstanceImpl.startNewSession(PhaseInstanceImpl.java:203)
        at io.hyperfoil.core.impl.PhaseInstanceImpl$ConstantPerSec.proceed(PhaseInstanceImpl.java:348)
        at io.hyperfoil.core.impl.PhaseInstanceImpl$ConstantPerSec.lambda$proceed$0(PhaseInstanceImpl.java:373)
        at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:139)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518)
        at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by rvansa** [comment]
Hopefully fixed in ef442e8a803e07a48e27619f2d1687ccb727a2c1
