### ISSUE TITLE
Hyperfoil fails to start if any info.json files are corrupt

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Hyperfoil#97]
If any `info.json` files are corrupt in the runs dir, Hypefoil fails to start with the following exception;

```
06:40:41,284 ERROR (vert.x-eventloop-thread-1) [i.h.H.Controller] Failed to deploy ControllerVerticle. io.vertx.core.json.DecodeException: Failed to decode:No content to map due to end-of-input
 at [Source: (String)""; line: 1, column: 0]
        at io.vertx.core.json.jackson.JacksonCodec.fromParser(JacksonCodec.java:97)
        at io.vertx.core.json.jackson.JacksonCodec.fromString(JacksonCodec.java:57)
        at io.vertx.core.json.JsonObject.fromJson(JsonObject.java:974)
        at io.vertx.core.json.JsonObject.<init>(JsonObject.java:54)
        at io.hyperfoil.clustering.ControllerVerticle.updateRuns(ControllerVerticle.java:269)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647)
        at io.hyperfoil.clustering.ControllerVerticle.start(ControllerVerticle.java:85)
        at io.vertx.core.Verticle.start(Verticle.java:66)
        at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:556)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518)
        at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (String)""; line: 1, column: 0]
        at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4146)
        at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3972)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2277)
        at io.vertx.core.json.jackson.JacksonCodec.fromParser(JacksonCodec.java:95)
        ... 19 more
```

Should capture this exception in ControllerVerticle.updateRuns() and handle appropriately

**Comment by rvansa** [comment]
Fixed.
